<?php

namespace Minicup\Model\Repository;

use LeanMapper\Entity;
use Minicup\Model\Entity\Category;
use Minicup\Model\Entity\Team;

class TeamRepository extends Repository
{
    /**
     * @param $slug string
     * @param $category Category
     * @return Team|NULL
     */
    public function getBySlug($slug, Category $category)
    {
        $row = $this->createFluent()
            ->where('[team_info.slug] = %s', $slug, 'AND [team.category_id] = ', $category->id)
            ->fetch();
        return $row ? $this->createEntity($row) : NULL;
    }

    public function findAll()
    {
        return $this->createEntities(
            $this->createFluent()
                ->fetchAll()
        );
    }

    /**
     * @see http://forum.dibiphp.com/cs/14592-lean-mapper-tenke-orm-nad-dibi#p104779
     * @param Entity $entity
     * @return mixed
     */
    public function persist(Entity $entity)
    {
        return parent::persist($entity); // TODO: Change the autogenerated stub
    }


}
