<?php

namespace Minicup\Model\Entity;

use LeanMapper\Entity;

/**
 * @property int            $id
 * @property int            $order = 0 order of team in table
 * @property int            $points points from actually played matches
 * @property int            $scored sum of scored goals
 * @property int            $received sum of received goals
 * @property Category       $category m:hasOne category where is team in
 * @property Match[]        $matches
 * @property int            $isActual = 1 is this in actual state?
 * @property Match|NULL     $afterMatch m:hasOne(after_match_id)
 * @property \DateTime      $inserted
 * @property TeamInfo       $i m:hasOne
 */
class Team extends Entity
{
    /**
     * for abbr request for slug or name
     * @param string $name
     * @return mixed|string
     * @inheritdoc
     */
    public function __get($name /*, array $filterArgs*/)
    {
        if (in_array($name, ['slug', 'name'])) {
            return $this->i->$name;
        }
        return parent::__get($name); // TODO: Change the autogenerated stub
    }
}
